"""
EEG Sleep Temporal PID — Plotting Script
==========================================

Reads CSVs generated by eeg_sleep_compute.py and produces all 15 plots
per electrode. Can also generate cross-electrode comparison plots.

Usage:
    python eeg_sleep_plot.py                       # all channels with data
    python eeg_sleep_plot.py --channels C3         # single channel
    python eeg_sleep_plot.py --channels C3 O1 F3   # subset
"""

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.patches import Patch
import seaborn as sns
from pathlib import Path
from datetime import datetime
import sys
import warnings
import argparse
import hashlib
import json

warnings.filterwarnings('ignore')

from scipy.stats import kruskal, mannwhitneyu, spearmanr, wilcoxon, levene
from itertools import combinations

# =============================================================================
# CONFIGURATION — loaded automatically from params JSON saved by compute script
# =============================================================================

SCRIPT_DIR = Path(__file__).parent
PROJECT_DIR = SCRIPT_DIR.parent.parent
RESULTS_DIR = PROJECT_DIR / "results" / "pid" / "eeg_sleep"


def _discover_all_params():
    """Return list of (params_dict, chash) for every params JSON with matching data."""
    if not RESULTS_DIR.exists():
        return []
    results = []
    for pf in sorted(RESULTS_DIR.glob("params_*.json"),
                     key=lambda p: p.stat().st_mtime):
        chash = pf.stem.split("_", 1)[1]
        with open(pf) as f:
            params = json.load(f)
        # check if any channel has data for this hash
        has_data = False
        bands = params.get("BANDS", None)
        for d in RESULTS_DIR.iterdir():
            if not d.is_dir():
                continue
            if (d / f"timeresolved_pid_filtered_{chash}.csv").exists():
                has_data = True
                break
            if bands:
                for b in bands:
                    if (d / b / f"timeresolved_pid_filtered_{chash}.csv").exists():
                        has_data = True
                        break
            if has_data:
                break
        if has_data:
            results.append((params, chash))
    return results


def _apply_params(params):
    """Set module-level config globals from a params dict."""
    global WINDOW_SEC, MAX_LAG_MIN, N_BINS, DISCRETIZE_PER_WINDOW
    global CONTINUOUS_STAGE_FILTER, DURATION_HOURS, BANDS
    global WINDOWS_PER_MIN, MIN_PER_WINDOW, MAX_LAG_WINDOWS
    WINDOW_SEC = params["WINDOW_SEC"]
    MAX_LAG_MIN = params["MAX_LAG_MIN"]
    N_BINS = params["N_BINS"]
    DISCRETIZE_PER_WINDOW = params["DISCRETIZE_PER_WINDOW"]
    CONTINUOUS_STAGE_FILTER = params["CONTINUOUS_STAGE_FILTER"]
    DURATION_HOURS = params["DURATION_HOURS"]
    BANDS = params.get("BANDS", None)
    WINDOWS_PER_MIN = 60 // WINDOW_SEC
    MIN_PER_WINDOW = WINDOW_SEC / 60
    MAX_LAG_WINDOWS = MAX_LAG_MIN * WINDOWS_PER_MIN


# initialise with first available config (or defaults)
_ALL_CONFIGS = _discover_all_params()
if _ALL_CONFIGS:
    _apply_params(_ALL_CONFIGS[0][0])
else:
    WINDOW_SEC = 30; MAX_LAG_MIN = 10; N_BINS = 4
    DISCRETIZE_PER_WINDOW = True; CONTINUOUS_STAGE_FILTER = False
    DURATION_HOURS = 4; BANDS = None
    WINDOWS_PER_MIN = 60 // WINDOW_SEC
    MIN_PER_WINDOW = WINDOW_SEC / 60
    MAX_LAG_WINDOWS = MAX_LAG_MIN * WINDOWS_PER_MIN

STAGE_COLORS = {
    'Wake': '#E8A317',
    'N1':   '#87CEEB',
    'N2':   '#4169E1',
    'N3':   '#191970',
    'REM':  '#DC143C',
    '?':    '#D3D3D3',
}
STAGE_ORDER = ['Wake', 'N1', 'N2', 'N3', 'REM']


def config_hash():
    params = (f"{WINDOW_SEC}_{MAX_LAG_MIN}_{N_BINS}_{DISCRETIZE_PER_WINDOW}"
              f"_{CONTINUOUS_STAGE_FILTER}_{DURATION_HOURS}")
    return hashlib.md5(params.encode()).hexdigest()[:8]


def benjamini_hochberg(pvals):
    pvals = np.asarray(pvals, dtype=float)
    n = len(pvals)
    if n == 0:
        return pvals
    order = np.argsort(pvals)
    adjusted = np.empty(n)
    adjusted[order[-1]] = pvals[order[-1]]
    for i in range(n - 2, -1, -1):
        adjusted[order[i]] = min(pvals[order[i]] * n / (i + 1),
                                  adjusted[order[i + 1]])
    return np.clip(adjusted, 0, 1)


# =============================================================================
# HELPERS
# =============================================================================

def add_stage_background(ax, stage_labels):
    for i, stage in enumerate(stage_labels):
        x0 = i * MIN_PER_WINDOW
        x1 = (i + 1) * MIN_PER_WINDOW
        ax.axvspan(x0, x1, alpha=0.15, color=STAGE_COLORS.get(stage, '#D3D3D3'),
                   linewidth=0)


def stage_legend_handles():
    return [Patch(facecolor=STAGE_COLORS[s], alpha=0.5, label=s) for s in STAGE_ORDER]


def common_lag_range(tr):
    present = [s for s in STAGE_ORDER if s in tr['stage'].unique()]
    if len(present) < 2:
        return tr
    sets = []
    for s in present:
        sub = tr[tr['stage'] == s]
        pairs = set(zip(sub['lag1_min'], sub['lag2_min']))
        sets.append(pairs)
    common = sets[0]
    for s in sets[1:]:
        common = common & s
    if len(common) == 0:
        return tr
    common_df = pd.DataFrame(list(common), columns=['lag1_min', 'lag2_min'])
    return tr.merge(common_df, on=['lag1_min', 'lag2_min'], how='inner')


def lag_index(df):
    """Return sorted unique lag values and a value→index mapping."""
    all_lags = sorted(set(df['lag1_min'].unique()) | set(df['lag2_min'].unique()))
    return all_lags, {v: i for i, v in enumerate(all_lags)}


def lag_tick_labels(lag_vals):
    """Compact tick labels: drop trailing zeros for whole numbers."""
    out = []
    for v in lag_vals:
        out.append(f'{v:g}')
    return out


def load_channel_data(ch_short, chash, band_name=None):
    """Load all CSVs/NPZ for one channel (optionally from a band subfolder).
    Returns dict of DataFrames or None if critical data is missing."""
    if band_name:
        ch_dir = RESULTS_DIR / ch_short / band_name
    else:
        ch_dir = RESULTS_DIR / ch_short
    if not ch_dir.exists():
        print(f"  WARNING: no data for {ch_short} at {ch_dir}")
        return None

    label = f"{ch_short}/{band_name}" if band_name else ch_short
    data = {'channel': label, 'ch_dir': ch_dir}

    f = ch_dir / f"global_pid_matrix_{chash}.csv"
    data['global'] = pd.read_csv(f) if f.exists() else None

    f = ch_dir / f"timeresolved_pid_filtered_{chash}.csv"
    data['tr'] = pd.read_csv(f) if f.exists() else None

    f = ch_dir / f"ar1_global_pid_mean_{chash}.csv"
    data['ar1_global'] = pd.read_csv(f) if f.exists() else None

    f = ch_dir / f"ar1_timeresolved_pid_filtered_{chash}.csv"
    data['ar1_tr'] = pd.read_csv(f) if f.exists() else None

    f = ch_dir / f"autocorrelation_{chash}.csv"
    data['autocorr'] = pd.read_csv(f) if f.exists() else None

    f = ch_dir / f"block_perm_null_{chash}.npz"
    if f.exists():
        data['null_vals'] = np.load(f)['null_vals']
    else:
        data['null_vals'] = None

    f = ch_dir / f"stage_labels_{chash}.csv"
    if f.exists():
        sl = pd.read_csv(f)
        data['stage_labels'] = sl['stage'].tolist()
    else:
        data['stage_labels'] = None

    return data


# =============================================================================
# PLOT FUNCTIONS — identical logic to eeg_sleep.py but parameterised by channel
# =============================================================================

def plot_global_matrix(results, channel, save_path=None):
    fig, axes = plt.subplots(2, 2, figsize=(12, 10))
    lag_vals, lag_idx = lag_index(results)
    n_lags = len(lag_vals)
    tick_labels = lag_tick_labels(lag_vals)
    comps  = ['redundancy', 'synergy', 'unique_0', 'unique_1']
    titles = ['Redundancy', 'Synergy', 'Unique (lag 1)', 'Unique (lag 2)']
    cmaps  = ['Greens', 'Reds', 'Blues', 'Purples']
    for ax, comp, title, cmap in zip(axes.flat, comps, titles, cmaps):
        mat = np.full((n_lags, n_lags), np.nan)
        for _, r in results.iterrows():
            mat[lag_idx[r['lag1_min']], lag_idx[r['lag2_min']]] = r[comp]
        sns.heatmap(mat, ax=ax, cmap=cmap, mask=np.isnan(mat),
                    xticklabels=tick_labels, yticklabels=tick_labels,
                    cbar_kws={'label': 'bits'})
        ax.set_title(title, fontweight='bold')
        ax.set_xlabel('Lag 2 (min)')
        ax.set_ylabel('Lag 1 (min)')
    plt.suptitle(f'Global Temporal PID — minute-scale lags\n'
                 f'({channel}, {DURATION_HOURS}h, {N_BINS} bins)',
                 fontsize=14, fontweight='bold')
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        plt.close()


def plot_combined_timeseries(tr, tr_ar1, stage_labels, channel, save_path=None):
    windows = sorted(tr['time_min'].unique())
    w_arr = np.array(windows)
    agg_act = tr.groupby('time_min').agg(
        redundancy=('redundancy', 'mean'), synergy=('synergy', 'mean'),
        unique_0=('unique_0', 'mean'), unique_1=('unique_1', 'mean'),
    ).reset_index()
    tr_u = tr.copy()
    tr_u['unique_total'] = tr_u['unique_0'] + tr_u['unique_1']
    pctiles = {}
    for col in ['redundancy', 'synergy', 'unique_total']:
        p10, p25, p75, p90 = [], [], [], []
        for ww in windows:
            vals = tr_u.loc[tr_u['time_min'] == ww, col].dropna()
            p10.append(np.percentile(vals, 10)); p25.append(np.percentile(vals, 25))
            p75.append(np.percentile(vals, 75)); p90.append(np.percentile(vals, 90))
        pctiles[col] = (np.array(p10), np.array(p25), np.array(p75), np.array(p90))
    agg_ar1 = tr_ar1.groupby('time_min').agg(
        redundancy=('redundancy', 'mean'), synergy=('synergy', 'mean'),
        unique_0=('unique_0', 'mean'), unique_1=('unique_1', 'mean'),
    ).reset_index()
    mrg = agg_act.merge(agg_ar1, on='time_min', suffixes=('', '_ar1'))
    t = mrg['time_min'].values
    fig, axes = plt.subplots(4, 1, figsize=(16, 12),
                             gridspec_kw={'height_ratios': [0.7, 1, 1, 1]}, sharex=True)
    stage_num = {'Wake': 0, 'REM': -0.5, 'N1': -1, 'N2': -2, 'N3': -3, '?': 0.5}
    hyp_y = [stage_num.get(s, 0.5) for s in stage_labels]
    hyp_x = np.arange(len(stage_labels)) * MIN_PER_WINDOW
    axes[0].step(hyp_x, hyp_y, where='post', color='black', lw=1.5)
    axes[0].set_yticks([0, -0.5, -1, -2, -3])
    axes[0].set_yticklabels(['Wake', 'REM', 'N1', 'N2', 'N3'])
    axes[0].set_ylabel('Stage'); axes[0].set_title('Hypnogram', fontweight='bold')
    add_stage_background(axes[0], stage_labels)
    axes[0].legend(handles=stage_legend_handles(), loc='upper right', ncol=5, fontsize=8, framealpha=0.8)
    axes[0].grid(axis='x', alpha=0.3)
    panels = [('redundancy', 'green', 'Redundancy'), ('synergy', 'red', 'Synergy')]
    for ax, (col, color, label) in zip(axes[1:3], panels):
        actual_v = mrg[col].values; ar1_v = mrg[f'{col}_ar1'].values
        p10, p25, p75, p90 = pctiles[col]
        ax.fill_between(w_arr, p10, p90, alpha=0.08, color=color, label='10–90 %ile')
        ax.fill_between(w_arr, p25, p75, alpha=0.18, color=color, label='25–75 %ile')
        ax.fill_between(t, ar1_v, alpha=0.3, color='gray', label='AR(1) baseline')
        ax.plot(t, actual_v, color=color, lw=1.5, label='Mean', zorder=3)
        ax.plot(t, actual_v - ar1_v, color=color, lw=1, ls='--', alpha=0.6, label='Excess', zorder=2)
        ax.axhline(0, color='black', lw=0.5, alpha=0.3)
        ax.set_ylabel(f'{label}\n(bits)'); ax.legend(loc='upper right', fontsize=7, ncol=2)
        add_stage_background(ax, stage_labels); ax.grid(axis='x', alpha=0.3)
    act_uniq = mrg['unique_0'].values + mrg['unique_1'].values
    ar1_uniq = mrg['unique_0_ar1'].values + mrg['unique_1_ar1'].values
    p10, p25, p75, p90 = pctiles['unique_total']
    axes[3].fill_between(w_arr, p10, p90, alpha=0.08, color='blue', label='10–90 %ile')
    axes[3].fill_between(w_arr, p25, p75, alpha=0.18, color='blue', label='25–75 %ile')
    axes[3].fill_between(t, ar1_uniq, alpha=0.3, color='gray', label='AR(1) baseline')
    axes[3].plot(t, act_uniq, color='blue', lw=1.5, label='Mean', zorder=3)
    axes[3].plot(t, act_uniq - ar1_uniq, color='blue', lw=1, ls='--', alpha=0.6, label='Excess', zorder=2)
    axes[3].axhline(0, color='black', lw=0.5, alpha=0.3)
    axes[3].set_ylabel('Total Unique\n(bits)'); axes[3].legend(loc='upper right', fontsize=7, ncol=2)
    add_stage_background(axes[3], stage_labels); axes[3].grid(axis='x', alpha=0.3)
    axes[-1].set_xlabel('Time (min)')
    plt.suptitle(f'Temporal PID evolution during sleep\n'
                 f'({channel}, mean + spread across lag pairs, AR(1) baseline)',
                 fontsize=14, fontweight='bold')
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight'); plt.close()


def plot_time_lag_heatmaps(tr, stage_labels, channel, save_path=None):
    subset = tr[tr['lag1_min'] == tr['lag1_min'].min()].copy()
    if subset.empty:
        return
    lag1_val = subset['lag1_min'].iloc[0]
    fig, axes = plt.subplots(3, 1, figsize=(16, 10), sharex=True)
    metrics = [('redundancy', 'Greens', 'Redundancy'), ('synergy', 'Reds', 'Synergy'),
               ('unique_0', 'Blues', 'Unique (lag 1)')]
    for ax, (col, cmap, label) in zip(axes, metrics):
        piv = subset.pivot_table(index='lag2_min', columns='time_min', values=col)
        sns.heatmap(piv, ax=ax, cmap=cmap, cbar_kws={'label': 'bits'},
                    xticklabels=10, yticklabels=1)
        ax.set_ylabel('Lag 2 (min)'); ax.set_title(label, fontweight='bold'); ax.invert_yaxis()
    axes[-1].set_xlabel('Time (min)')
    plt.suptitle(f'Time × Lag heatmap (lag1 fixed at {lag1_val:g} min)\n({channel}, {N_BINS} bins)',
                 fontsize=14, fontweight='bold')
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight'); plt.close()


def plot_stage_comparison(tr, channel, save_path=None):
    tr_common = common_lag_range(tr)
    n_common = len(tr_common[['lag1_min', 'lag2_min']].drop_duplicates())
    agg = tr_common.groupby(['time_min', 'stage']).agg(
        redundancy=('redundancy', 'mean'), synergy=('synergy', 'mean'),
        unique_0=('unique_0', 'mean'), unique_1=('unique_1', 'mean'),
    ).reset_index()
    agg['unique_total'] = agg['unique_0'] + agg['unique_1']
    agg['ratio'] = agg['synergy'] / agg['redundancy'].replace(0, np.nan)
    agg = agg[agg['stage'].isin(STAGE_ORDER)]
    fig, axes = plt.subplots(1, 4, figsize=(18, 6))
    palette = {s: STAGE_COLORS[s] for s in STAGE_ORDER}
    metrics = [('redundancy', 'Redundancy (bits)'), ('synergy', 'Synergy (bits)'),
               ('unique_total', 'Total Unique (bits)'), ('ratio', 'Synergy / Redundancy')]
    for ax, (col, ylabel) in zip(axes, metrics):
        sns.boxplot(data=agg, x='stage', y=col, order=STAGE_ORDER,
                    palette=palette, ax=ax, showfliers=False, width=0.6)
        ax.set_xlabel('Sleep stage'); ax.set_ylabel(ylabel)
        ax.set_title(col.replace('_', ' ').title() if col != 'ratio' else 'S / R Ratio',
                     fontweight='bold')
        ax.grid(axis='y', alpha=0.3)
        if col == 'ratio':
            ax.axhline(1.0, color='grey', ls='--', alpha=0.6, label='S = R'); ax.legend(fontsize=8)
        groups = [agg.loc[agg['stage'] == s, col].dropna().values
                  for s in STAGE_ORDER if len(agg.loc[agg['stage'] == s, col].dropna()) > 0]
        if len(groups) >= 2:
            H, p_kw = kruskal(*groups)
            sig_str = '***' if p_kw < 0.001 else '**' if p_kw < 0.01 else '*' if p_kw < 0.05 else 'n.s.'
            ax.set_title(f"{ax.get_title()}\nKW: H={H:.1f}, p={p_kw:.1e} {sig_str}",
                         fontweight='bold', fontsize=10)
        present = [s for s in STAGE_ORDER if len(agg.loc[agg['stage'] == s, col].dropna()) >= 3]
        all_pairs, all_pvals = [], []
        for s1, s2 in combinations(present, 2):
            v1 = agg.loc[agg['stage'] == s1, col].dropna().values
            v2 = agg.loc[agg['stage'] == s2, col].dropna().values
            if len(v1) >= 3 and len(v2) >= 3:
                _, p_mw = mannwhitneyu(v1, v2, alternative='two-sided')
                all_pairs.append((s1, s2, p_mw)); all_pvals.append(p_mw)
        sig_pairs = []
        if all_pvals:
            adj_pvals = benjamini_hochberg(all_pvals)
            for (s1, s2, _), p_adj in zip(all_pairs, adj_pvals):
                if p_adj < 0.05:
                    sig_pairs.append((s1, s2, p_adj))
        sig_pairs.sort(key=lambda x: x[2])
        y_max = agg[col].dropna().quantile(0.95) if len(agg[col].dropna()) > 0 else 1
        y_step = y_max * 0.08
        for rank, (s1, s2, p_val) in enumerate(sig_pairs[:4]):
            x1 = STAGE_ORDER.index(s1); x2 = STAGE_ORDER.index(s2)
            y_bar = y_max + y_step * (rank + 1)
            ax.plot([x1, x1, x2, x2], [y_bar - y_step*0.2, y_bar, y_bar, y_bar - y_step*0.2],
                    color='black', lw=0.8)
            stars = '***' if p_val < 0.001 else '**' if p_val < 0.01 else '*'
            ax.text((x1 + x2) / 2, y_bar, stars, ha='center', va='bottom', fontsize=8)
    plt.suptitle(f'PID by sleep stage ({channel}, {n_common} common lag pairs)',
                 fontsize=14, fontweight='bold')
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight'); plt.close()


def plot_lagdiff_heatmap(tr, stage_labels, channel, save_path=None):
    tr = tr.copy()
    tr['lag_diff'] = tr['lag2_min'] - tr['lag1_min']
    fig, axes = plt.subplots(3, 1, figsize=(16, 10), sharex=True)
    metrics = [('redundancy', 'Greens', 'Redundancy'), ('synergy', 'Reds', 'Synergy'),
               ('unique_0', 'Blues', 'Unique (lag 1)')]
    for ax, (col, cmap, label) in zip(axes, metrics):
        piv = tr.pivot_table(index='lag_diff', columns='time_min', values=col, aggfunc='mean')
        sns.heatmap(piv, ax=ax, cmap=cmap, cbar_kws={'label': 'bits'},
                    xticklabels=10, yticklabels=1)
        ax.set_ylabel('Lag diff (min)'); ax.set_title(label, fontweight='bold'); ax.invert_yaxis()
    axes[-1].set_xlabel('Time (min)')
    plt.suptitle(f'Time × Lag-difference heatmap\n({channel})', fontsize=14, fontweight='bold')
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight'); plt.close()


def plot_global_matrix_vs_ar1(actual, ar1_mean, channel, save_path=None):
    merged = actual.merge(ar1_mean, on=['lag1_min', 'lag2_min'], suffixes=('', '_ar1'), how='inner')
    ar1_df = merged[['lag1_min', 'lag2_min'] +
                    [f'{m}_ar1' for m in ['redundancy', 'synergy', 'unique_0', 'unique_1']]].copy()
    ar1_df.columns = ['lag1_min', 'lag2_min', 'redundancy', 'synergy', 'unique_0', 'unique_1']
    actual_df = merged[['lag1_min', 'lag2_min', 'redundancy', 'synergy', 'unique_0', 'unique_1']].copy()
    excess = actual_df.copy()
    for m in ['redundancy', 'synergy', 'unique_0', 'unique_1']:
        excess[m] = actual_df[m].values - ar1_df[m].values
    fig, axes = plt.subplots(3, 4, figsize=(18, 12))
    lag_vals, l_idx = lag_index(actual_df)
    n_lags = len(lag_vals)
    tick_labels = lag_tick_labels(lag_vals)
    comps = ['redundancy', 'synergy', 'unique_0', 'unique_1']
    labels = ['Redundancy', 'Synergy', 'Unique₁', 'Unique₂']
    cmaps = ['Greens', 'Reds', 'Blues', 'Purples']
    row_dfs = [actual_df, ar1_df, excess]
    row_labels = ['Actual', 'AR(1) baseline', 'Excess (Actual − AR(1))']
    for ri, (df_r, row_lab) in enumerate(zip(row_dfs, row_labels)):
        for ci, (comp, lab, cmap) in enumerate(zip(comps, labels, cmaps)):
            ax = axes[ri, ci]
            mat = np.full((n_lags, n_lags), np.nan)
            for _, r in df_r.iterrows():
                i1 = l_idx.get(r['lag1_min']); i2 = l_idx.get(r['lag2_min'])
                if i1 is not None and i2 is not None:
                    mat[i1, i2] = r[comp]
            if ri < 2:
                sns.heatmap(mat, ax=ax, cmap=cmap, mask=np.isnan(mat),
                            xticklabels=tick_labels, yticklabels=tick_labels, cbar_kws={'label': 'bits'})
            else:
                vmax = np.nanmax(np.abs(mat)) if not np.all(np.isnan(mat)) else 1e-6
                sns.heatmap(mat, ax=ax, cmap='RdBu_r', mask=np.isnan(mat), center=0,
                            vmin=-vmax, vmax=vmax, xticklabels=tick_labels, yticklabels=tick_labels,
                            cbar_kws={'label': 'bits'})
            if ri == 0: ax.set_title(lab, fontweight='bold')
            ax.set_xlabel('Lag 2 (min)' if ri == 2 else '')
            ax.set_ylabel(f'{row_lab}\nLag 1 (min)' if ci == 0 else '')
    plt.suptitle(f'Global PID: Actual vs AR(1) Baseline\n({channel}, {N_BINS} bins)',
                 fontsize=14, fontweight='bold')
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight'); plt.close()


def plot_stage_comparison_vs_ar1(tr_actual, tr_ar1, channel, save_path=None):
    tr_actual_c = common_lag_range(tr_actual); tr_ar1_c = common_lag_range(tr_ar1)
    def _agg(df):
        a = df.groupby(['time_min', 'stage']).agg(
            redundancy=('redundancy', 'mean'), synergy=('synergy', 'mean'),
            unique_0=('unique_0', 'mean'), unique_1=('unique_1', 'mean'),
        ).reset_index()
        a['unique_total'] = a['unique_0'] + a['unique_1']
        return a[a['stage'].isin(STAGE_ORDER)]
    agg_act = _agg(tr_actual_c); agg_ar1 = _agg(tr_ar1_c)
    mrg = agg_act.merge(agg_ar1, on=['time_min', 'stage'], suffixes=('', '_ar1'))
    for m in ['redundancy', 'synergy', 'unique_total']:
        mrg[f'{m}_excess'] = mrg[m] - mrg.get(f'{m}_ar1', 0)
    fig, axes = plt.subplots(2, 3, figsize=(16, 9))
    palette = {s: STAGE_COLORS[s] for s in STAGE_ORDER}
    metrics = ['redundancy', 'synergy', 'unique_total']
    labels_m = ['Redundancy', 'Synergy', 'Total Unique']
    for ax, m, lab in zip(axes[0], metrics, labels_m):
        a_plot = agg_act[['stage', m]].copy(); a_plot['source'] = 'Actual'
        s_plot = agg_ar1[['stage']].copy()
        s_plot[m] = agg_ar1[m].values if m != 'unique_total' else \
            agg_ar1['unique_0'].values + agg_ar1['unique_1'].values
        s_plot['source'] = 'AR(1)'
        combined = pd.concat([a_plot, s_plot], ignore_index=True)
        sns.boxplot(data=combined, x='stage', y=m, hue='source', order=STAGE_ORDER,
                    palette={'Actual': 'steelblue', 'AR(1)': 'lightgray'},
                    ax=ax, showfliers=False, width=0.7)
        ax.set_title(lab, fontweight='bold'); ax.set_ylabel(f'{lab} (bits)'); ax.set_xlabel('')
        ax.grid(axis='y', alpha=0.3)
        if ax != axes[0, 0]: ax.get_legend().remove()
        else: ax.legend(fontsize=8)
    for ax, m, lab in zip(axes[0], metrics, labels_m):
        y_top = ax.get_ylim()[1]
        for i, s in enumerate(STAGE_ORDER):
            a_vals = agg_act.loc[agg_act['stage'] == s, m].dropna().values
            b_vals = agg_ar1.loc[agg_ar1['stage'] == s, m].dropna().values
            if m == 'unique_total':
                b_vals = (agg_ar1.loc[agg_ar1['stage'] == s, 'unique_0'].values
                          + agg_ar1.loc[agg_ar1['stage'] == s, 'unique_1'].values)
            n_pair = min(len(a_vals), len(b_vals))
            if n_pair > 10:
                try:
                    _, p_w = wilcoxon(a_vals[:n_pair], b_vals[:n_pair])
                    star = '***' if p_w < 0.001 else '**' if p_w < 0.01 else '*' if p_w < 0.05 else 'n.s.'
                    ax.text(i, y_top * 0.97, star, ha='center', fontsize=8, fontweight='bold', color='black')
                except Exception:
                    pass
    for ax, m, lab in zip(axes[1], metrics, labels_m):
        col = f'{m}_excess'
        sns.boxplot(data=mrg, x='stage', y=col, order=STAGE_ORDER,
                    palette=palette, ax=ax, showfliers=False)
        ax.axhline(0, color='gray', ls='--', lw=1, alpha=0.6)
        ax.set_ylabel('Excess (bits)'); ax.set_xlabel('Sleep stage'); ax.grid(axis='y', alpha=0.3)
        groups = [mrg.loc[mrg['stage'] == s, col].dropna().values
                  for s in STAGE_ORDER if len(mrg.loc[mrg['stage'] == s, col].dropna()) > 0]
        if len(groups) >= 2:
            H, p = kruskal(*groups)
            ax.set_title(f'Excess {lab}\nKW: H={H:.1f}, p={p:.1e}', fontweight='bold')
        else:
            ax.set_title(f'Excess {lab} (nonlinear)', fontweight='bold')
    plt.suptitle(f'PID: Actual vs AR(1) Baseline ({channel})', fontsize=14, fontweight='bold')
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight'); plt.close()


def plot_autocorrelation_vs_pid(autocorr_df, tr, stage_labels, channel, save_path=None):
    fig, axes = plt.subplots(3, 1, figsize=(16, 12), gridspec_kw={'height_ratios': [1, 1, 1.2]})
    ac_piv = autocorr_df.pivot_table(index='lag_min', columns='time_min', values='autocorr')
    sns.heatmap(ac_piv, ax=axes[0], cmap='RdBu_r', center=0, vmin=-1, vmax=1,
                cbar_kws={'label': 'R(τ)'}, xticklabels=10, yticklabels=1)
    axes[0].set_ylabel('Lag (min)'); axes[0].set_title('Cross-window autocorrelation R(τ)', fontweight='bold')
    axes[0].invert_yaxis()
    subset = tr[tr['lag1_min'] == tr['lag1_min'].min()].copy()
    lag1_val = tr['lag1_min'].min()
    if not subset.empty:
        piv_syn = subset.pivot_table(index='lag2_min', columns='time_min', values='synergy')
        sns.heatmap(piv_syn, ax=axes[1], cmap='Reds', cbar_kws={'label': 'bits'},
                    xticklabels=10, yticklabels=1)
        axes[1].set_ylabel('Lag₂ (min)'); axes[1].set_title(f'Synergy (lag₁ = {lag1_val:g} min)', fontweight='bold')
        axes[1].invert_yaxis()
    from matplotlib.colors import ListedColormap
    from mpl_toolkits.axes_grid1.inset_locator import inset_axes
    valid_times = sorted(autocorr_df['time_min'].unique())
    stage_arr = np.array([[STAGE_ORDER.index(stage_labels[int(round(t / MIN_PER_WINDOW))])
                           if int(round(t / MIN_PER_WINDOW)) < len(stage_labels) and
                              stage_labels[int(round(t / MIN_PER_WINDOW))] in STAGE_ORDER
                           else -1 for t in valid_times]])
    stage_cmap = ListedColormap([STAGE_COLORS[s] for s in STAGE_ORDER])
    stage_ax = inset_axes(axes[0], width='100%', height='8%', loc='upper center',
                          bbox_to_anchor=(0, 1.12, 1, 1), bbox_transform=axes[0].transAxes, borderpad=0)
    stage_ax.imshow(stage_arr, aspect='auto', cmap=stage_cmap, vmin=0, vmax=len(STAGE_ORDER) - 1)
    stage_ax.set_yticks([]); stage_ax.set_xticks([]); stage_ax.set_title('Sleep stage', fontsize=9)
    ac_mean = autocorr_df.groupby('time_min')['autocorr'].mean().reset_index()
    ac_mean.columns = ['time_min', 'mean_autocorr']
    pid_mean = tr.groupby('time_min').agg(synergy=('synergy', 'mean'), redundancy=('redundancy', 'mean')).reset_index()
    sc = ac_mean.merge(pid_mean, on='time_min')
    sc['stage'] = sc['time_min'].map(
        lambda w: stage_labels[int(round(w / MIN_PER_WINDOW))]
                  if int(round(w / MIN_PER_WINDOW)) < len(stage_labels) else '?')
    sc = sc[sc['stage'].isin(STAGE_ORDER)]
    for s in STAGE_ORDER:
        sub = sc[sc['stage'] == s]
        axes[2].scatter(sub['mean_autocorr'], sub['synergy'], c=STAGE_COLORS[s], label=s, alpha=0.6, s=20, edgecolors='none')
    valid_sc = sc.dropna(subset=['mean_autocorr', 'synergy'])
    if len(valid_sc) > 5:
        rho, p_sp = spearmanr(valid_sc['mean_autocorr'], valid_sc['synergy'])
        axes[2].set_title(f'Autocorrelation vs Synergy\nSpearman ρ={rho:.3f}, p={p_sp:.1e}', fontweight='bold')
    else:
        axes[2].set_title('Autocorrelation vs Synergy per window', fontweight='bold')
    axes[2].set_xlabel('Mean autocorrelation R(τ)'); axes[2].set_ylabel('Mean synergy (bits)')
    axes[2].legend(fontsize=8); axes[2].grid(alpha=0.3)
    plt.suptitle(f'Autocorrelation structure vs PID\n({channel})', fontsize=14, fontweight='bold', y=0.99)
    plt.tight_layout(rect=[0, 0, 1, 0.93])
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight'); plt.close()


def plot_sr_ratio_vs_autocorr(autocorr_df, tr, channel, save_path=None):
    ac_mean = autocorr_df.groupby('time_min')['autocorr'].mean().reset_index()
    ac_mean.columns = ['time_min', 'mean_autocorr']
    pid_agg = tr.groupby(['time_min', 'stage']).agg(synergy=('synergy', 'mean'), redundancy=('redundancy', 'mean')).reset_index()
    pid_agg['sr_ratio'] = pid_agg['synergy'] / pid_agg['redundancy'].replace(0, np.nan)
    sc = pid_agg.merge(ac_mean, on='time_min'); sc = sc[sc['stage'].isin(STAGE_ORDER)]
    fig, axes = plt.subplots(1, 3, figsize=(18, 6))
    legend_entries = []
    for s in STAGE_ORDER:
        sub = sc[sc['stage'] == s]
        axes[0].scatter(sub['mean_autocorr'], sub['sr_ratio'], c=STAGE_COLORS[s], alpha=0.5, s=20, edgecolors='none')
        valid = sub.dropna(subset=['mean_autocorr', 'sr_ratio'])
        if len(valid) > 5:
            z = np.polyfit(valid['mean_autocorr'], valid['sr_ratio'], 1)
            x_line = np.linspace(valid['mean_autocorr'].min(), valid['mean_autocorr'].max(), 50)
            axes[0].plot(x_line, np.polyval(z, x_line), color=STAGE_COLORS[s], lw=2, alpha=0.7)
            rho, p_sp = spearmanr(valid['mean_autocorr'], valid['sr_ratio'])
            legend_entries.append(f'{s}: ρ={rho:.2f}, p={p_sp:.1e}')
        else:
            legend_entries.append(s)
    axes[0].axhline(1.0, color='grey', ls='--', alpha=0.5)
    for i, s in enumerate(STAGE_ORDER):
        if i < len(legend_entries):
            axes[0].plot([], [], color=STAGE_COLORS[s], lw=2, label=legend_entries[i])
    axes[0].plot([], [], color='grey', ls='--', label='S = R')
    axes[0].set_xlabel('Mean autocorrelation R(τ)'); axes[0].set_ylabel('Synergy / Redundancy')
    axes[0].set_title('S/R ratio vs Autocorrelation', fontweight='bold')
    axes[0].legend(fontsize=7, ncol=1); axes[0].grid(alpha=0.3)
    sns.boxplot(data=sc, x='stage', y='sr_ratio', order=STAGE_ORDER, palette=STAGE_COLORS, ax=axes[1], showfliers=False)
    axes[1].axhline(1.0, color='grey', ls='--', alpha=0.5, label='S = R')
    axes[1].set_xlabel('Sleep stage'); axes[1].set_ylabel('Synergy / Redundancy')
    sr_groups = [sc.loc[sc['stage'] == s, 'sr_ratio'].dropna().values for s in STAGE_ORDER if len(sc.loc[sc['stage'] == s, 'sr_ratio'].dropna()) > 0]
    if len(sr_groups) >= 2:
        H, p = kruskal(*sr_groups)
        axes[1].set_title(f'S/R ratio by stage\nKW: H={H:.1f}, p={p:.1e}', fontweight='bold')
    else:
        axes[1].set_title('S/R ratio by stage', fontweight='bold')
    axes[1].legend(fontsize=8); axes[1].grid(axis='y', alpha=0.3)
    sns.boxplot(data=sc, x='stage', y='mean_autocorr', order=STAGE_ORDER, palette=STAGE_COLORS, ax=axes[2], showfliers=False)
    axes[2].set_xlabel('Sleep stage'); axes[2].set_ylabel('Mean autocorrelation R(τ)')
    axes[2].set_title('Autocorrelation by stage', fontweight='bold'); axes[2].grid(axis='y', alpha=0.3)
    plt.suptitle(f'Diagnostic: Is S/R ratio explained by autocorrelation? ({channel})', fontsize=13, fontweight='bold')
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight'); plt.close()


def plot_pid_per_stage_matrix(tr, channel, save_path=None):
    present = [s for s in STAGE_ORDER if s in tr['stage'].unique()]
    n_stages = len(present)
    if n_stages == 0: return
    fig, axes = plt.subplots(2, n_stages, figsize=(4 * n_stages, 8))
    if n_stages == 1: axes = axes.reshape(2, 1)
    lag_vals, l_idx = lag_index(tr)
    n_lags = len(lag_vals)
    tick_labels = lag_tick_labels(lag_vals)
    for ci, stage in enumerate(present):
        sub = tr[tr['stage'] == stage]
        for ri, (metric, cmap, label) in enumerate([('synergy', 'Reds', 'Synergy'), ('redundancy', 'Greens', 'Redundancy')]):
            ax = axes[ri, ci]
            piv = sub.pivot_table(index='lag1_min', columns='lag2_min', values=metric, aggfunc='mean')
            mat = np.full((n_lags, n_lags), np.nan)
            for l1v in piv.index:
                for l2v in piv.columns:
                    val = piv.loc[l1v, l2v]
                    if not np.isnan(val) and l1v in l_idx and l2v in l_idx:
                        mat[l_idx[l1v], l_idx[l2v]] = val
            sns.heatmap(mat, ax=ax, cmap=cmap, mask=np.isnan(mat), cbar_kws={'label': 'bits', 'shrink': 0.7},
                        xticklabels=tick_labels, yticklabels=tick_labels)
            if ri == 0:
                ax.set_title(f'{stage}\n(n={len(sub["time_min"].unique())} windows)',
                             fontweight='bold', color=STAGE_COLORS.get(stage, 'black'))
            if ci == 0: ax.set_ylabel(f'{label}\nLag 1 (min)')
            else: ax.set_ylabel('')
            ax.set_xlabel('Lag 2 (min)' if ri == 1 else '')
    plt.suptitle(f'PID atom matrices by sleep stage ({channel})', fontsize=14, fontweight='bold')
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight'); plt.close()


def plot_atom_fractions(tr, channel, save_path=None):
    tr_common = common_lag_range(tr)
    agg = tr_common.groupby(['time_min', 'stage']).agg(
        redundancy=('redundancy', 'mean'), synergy=('synergy', 'mean'),
        unique_0=('unique_0', 'mean'), unique_1=('unique_1', 'mean'),
    ).reset_index()
    agg = agg[agg['stage'].isin(STAGE_ORDER)]
    agg['total'] = agg['redundancy'] + agg['synergy'] + agg['unique_0'] + agg['unique_1']
    for col in ['redundancy', 'synergy', 'unique_0', 'unique_1']:
        agg[f'{col}_frac'] = agg[col] / agg['total'].replace(0, np.nan)
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    sns.boxplot(data=agg, x='stage', y='total', order=STAGE_ORDER, palette=STAGE_COLORS, ax=axes[0], showfliers=False)
    axes[0].set_ylabel('Total MI (bits)'); axes[0].set_xlabel('Sleep stage')
    axes[0].set_title('Total mutual information', fontweight='bold'); axes[0].grid(axis='y', alpha=0.3)
    groups = [agg.loc[agg['stage'] == s, 'total'].dropna().values for s in STAGE_ORDER if len(agg.loc[agg['stage'] == s, 'total'].dropna()) > 0]
    if len(groups) >= 2:
        H, p = kruskal(*groups)
        axes[0].set_title(f'Total MI\nKW: H={H:.1f}, p={p:.1e}', fontweight='bold')
    frac_means = agg.groupby('stage')[['redundancy_frac', 'synergy_frac', 'unique_0_frac', 'unique_1_frac']].mean()
    frac_means = frac_means.reindex(STAGE_ORDER).dropna(how='all')
    bar_colors = ['green', 'red', 'steelblue', 'mediumpurple']
    bar_labels = ['Redundancy', 'Synergy', 'Unique₁', 'Unique₂']
    bottom = np.zeros(len(frac_means)); x = np.arange(len(frac_means))
    for col, color, label in zip(['redundancy_frac', 'synergy_frac', 'unique_0_frac', 'unique_1_frac'], bar_colors, bar_labels):
        vals = frac_means[col].values
        axes[1].bar(x, vals, bottom=bottom, color=color, label=label, alpha=0.8, edgecolor='white', linewidth=0.5)
        bottom += vals
    axes[1].set_xticks(x); axes[1].set_xticklabels(frac_means.index)
    axes[1].set_ylabel('Fraction of total MI'); axes[1].set_xlabel('Sleep stage')
    axes[1].set_ylim(0, 1.05); axes[1].grid(axis='y', alpha=0.3)
    syn_frac_groups = [agg.loc[agg['stage'] == s, 'synergy_frac'].dropna().values for s in STAGE_ORDER if len(agg.loc[agg['stage'] == s, 'synergy_frac'].dropna()) > 0]
    if len(syn_frac_groups) >= 2:
        H, p = kruskal(*syn_frac_groups)
        axes[1].set_title(f'PID atom composition\nSynergy frac. KW: H={H:.1f}, p={p:.1e}', fontweight='bold')
    else:
        axes[1].set_title('PID atom composition', fontweight='bold')
    axes[1].legend(fontsize=8, loc='upper right')
    plt.suptitle(f'Information quantity vs. composition ({channel})', fontsize=14, fontweight='bold')
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight'); plt.close()


def plot_nrem_rem_cycles(tr, stage_labels, channel, save_path=None):
    rem_onsets = []
    in_rem = False
    for i, s in enumerate(stage_labels):
        if s == 'REM' and not in_rem: rem_onsets.append(i); in_rem = True
        elif s != 'REM': in_rem = False
    if len(rem_onsets) < 1: return
    half_win = 15
    agg = tr.groupby('time_min').agg(redundancy=('redundancy', 'mean'), synergy=('synergy', 'mean'),
        unique_0=('unique_0', 'mean'), unique_1=('unique_1', 'mean')).reset_index()
    agg['unique_total'] = agg['unique_0'] + agg['unique_1']
    aligned = []
    for onset_win in rem_onsets:
        onset_min = onset_win * MIN_PER_WINDOW
        for _, row in agg.iterrows():
            dt = row['time_min'] - onset_min
            if -half_win <= dt <= half_win:
                aligned.append({'dt': dt, 'redundancy': row['redundancy'], 'synergy': row['synergy'],
                                'unique_total': row['unique_total'], 'cycle': rem_onsets.index(onset_win)})
    if not aligned: return
    df_al = pd.DataFrame(aligned)
    fig, axes = plt.subplots(3, 1, figsize=(12, 9), sharex=True)
    for ax, (col, color, label) in zip(axes, [('redundancy', 'green', 'Redundancy'), ('synergy', 'red', 'Synergy'), ('unique_total', 'blue', 'Total Unique')]):
        means = df_al.groupby('dt')[col].agg(['mean', 'sem']).reset_index()
        ax.plot(means['dt'], means['mean'], color=color, lw=2)
        ax.fill_between(means['dt'], means['mean'] - means['sem'], means['mean'] + means['sem'], color=color, alpha=0.2)
        ax.axvline(0, color='red', ls='--', lw=1.5, alpha=0.7, label='REM onset')
        ax.set_ylabel(f'{label}\n(bits)'); ax.legend(fontsize=8); ax.grid(alpha=0.3)
    axes[-1].set_xlabel('Time relative to REM onset (min)')
    plt.suptitle(f'PID dynamics around NREM→REM transitions ({channel})\n(n={len(rem_onsets)} cycles, mean ± SEM)',
                 fontsize=14, fontweight='bold')
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight'); plt.close()


def plot_effect_sizes(tr, channel, save_path=None):
    tr_common = common_lag_range(tr)
    agg = tr_common.groupby(['time_min', 'stage']).agg(
        redundancy=('redundancy', 'mean'), synergy=('synergy', 'mean'),
        unique_0=('unique_0', 'mean'), unique_1=('unique_1', 'mean'),
    ).reset_index()
    agg['unique_total'] = agg['unique_0'] + agg['unique_1']
    agg['ratio'] = agg['synergy'] / agg['redundancy'].replace(0, np.nan)
    agg = agg[agg['stage'].isin(STAGE_ORDER)]
    present = [s for s in STAGE_ORDER if s in agg['stage'].unique()]
    fig, axes = plt.subplots(1, 4, figsize=(18, 4))
    for ax, metric, label in zip(axes, ['redundancy', 'synergy', 'unique_total', 'ratio'],
                                  ['Redundancy', 'Synergy', 'Total Unique', 'S/R Ratio']):
        n = len(present); d_mat = np.full((n, n), np.nan); p_mat = np.full((n, n), np.nan)
        for i, s1 in enumerate(present):
            for j, s2 in enumerate(present):
                if i >= j: continue
                v1 = agg.loc[agg['stage'] == s1, metric].dropna().values
                v2 = agg.loc[agg['stage'] == s2, metric].dropna().values
                if len(v1) < 3 or len(v2) < 3: continue
                pooled_std = np.sqrt(((len(v1)-1)*np.var(v1, ddof=1) + (len(v2)-1)*np.var(v2, ddof=1)) / (len(v1) + len(v2) - 2))
                if pooled_std > 0:
                    d_mat[i, j] = (np.mean(v1) - np.mean(v2)) / pooled_std; d_mat[j, i] = -d_mat[i, j]
                _, p_val = mannwhitneyu(v1, v2, alternative='two-sided'); p_mat[i, j] = p_val; p_mat[j, i] = p_val
        upper_p, upper_idx = [], []
        for i in range(n):
            for j in range(i + 1, n):
                if not np.isnan(p_mat[i, j]): upper_p.append(p_mat[i, j]); upper_idx.append((i, j))
        p_mat_fdr = np.full((n, n), np.nan)
        if upper_p:
            adj_p = benjamini_hochberg(upper_p)
            for (i, j), ap in zip(upper_idx, adj_p): p_mat_fdr[i, j] = ap; p_mat_fdr[j, i] = ap
        vmax = np.nanmax(np.abs(d_mat)) if not np.all(np.isnan(d_mat)) else 1
        sns.heatmap(d_mat, ax=ax, cmap='RdBu_r', center=0, vmin=-vmax, vmax=vmax,
                    xticklabels=present, yticklabels=present, annot=True, fmt='.2f',
                    annot_kws={'fontsize': 8}, cbar_kws={'label': "Cohen's d", 'shrink': 0.8}, mask=np.isnan(d_mat))
        for i in range(n):
            for j in range(n):
                if not np.isnan(p_mat_fdr[i, j]) and p_mat_fdr[i, j] < 0.05:
                    ax.text(j + 0.5, i + 0.8, '*', ha='center', va='center', fontsize=10, fontweight='bold')
        ax.set_title(label, fontweight='bold')
    plt.suptitle(f"Effect sizes (Cohen's d) between sleep stages ({channel})\n(* = FDR p < 0.05)",
                 fontsize=13, fontweight='bold')
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight'); plt.close()


def plot_block_permutation(global_results, null_vals, channel, save_path=None):
    lag_vals, l_idx = lag_index(global_results)
    n_lags = len(lag_vals)
    tick_labels = lag_tick_labels(lag_vals)
    # rebuild lag_pairs in window units to match null_vals ordering
    max_lag_w = MAX_LAG_MIN * WINDOWS_PER_MIN
    lag_pairs_w = [(l1, l2) for l1 in range(1, max_lag_w) for l2 in range(l1 + 1, max_lag_w + 1)]
    fig, axes = plt.subplots(2, 2, figsize=(12, 10))
    comps = ['redundancy', 'synergy', 'unique_0', 'unique_1']
    titles = ['Redundancy', 'Synergy', 'Unique₁', 'Unique₂']
    cmaps = ['Greens', 'Reds', 'Blues', 'Purples']
    comp_idx = {c: i for i, c in enumerate(comps)}
    min_per_w = MIN_PER_WINDOW
    for ax, comp, title, cmap in zip(axes.flat, comps, titles, cmaps):
        p_mat = np.full((n_lags, n_lags), np.nan); ci = comp_idx[comp]
        for li, (l1w, l2w) in enumerate(lag_pairs_w):
            l1_min = round(l1w * min_per_w, 4)
            l2_min = round(l2w * min_per_w, 4)
            row = global_results[(global_results['lag1_min'] == l1_min) & (global_results['lag2_min'] == l2_min)]
            if row.empty: continue
            observed = row[comp].values[0]; null_dist = null_vals[:, li, ci]
            p = (np.sum(null_dist >= observed) + 1) / (len(null_dist) + 1)
            if l1_min in l_idx and l2_min in l_idx:
                p_mat[l_idx[l1_min], l_idx[l2_min]] = -np.log10(max(p, 1e-10))
        sns.heatmap(p_mat, ax=ax, cmap=cmap, mask=np.isnan(p_mat), xticklabels=tick_labels, yticklabels=tick_labels,
                    cbar_kws={'label': '-log₁₀(p)'})
        for l1i in range(n_lags):
            for l2i in range(n_lags):
                if not np.isnan(p_mat[l1i, l2i]) and p_mat[l1i, l2i] > -np.log10(0.05):
                    ax.text(l2i + 0.5, l1i + 0.5, '*', ha='center', va='center', fontsize=12, fontweight='bold', color='white')
        ax.set_title(title, fontweight='bold'); ax.set_xlabel('Lag 2 (min)'); ax.set_ylabel('Lag 1 (min)')
    plt.suptitle(f'Block-permutation significance ({channel})\n(n={null_vals.shape[0]} perms, * = p < 0.05)',
                 fontsize=14, fontweight='bold')
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight'); plt.close()


def plot_optimal_timescales(tr, channel, save_path=None):
    tr = tr.copy()
    tr['mean_lag'] = (tr['lag1_min'] + tr['lag2_min']) / 2.0
    tr = tr[tr['stage'].isin(STAGE_ORDER)]
    atoms = [('synergy', 'red', 'Synergy'), ('redundancy', 'green', 'Redundancy'), ('unique_total', 'blue', 'Total Unique')]
    tr['unique_total'] = tr['unique_0'] + tr['unique_1']
    fig = plt.figure(figsize=(18, 14)); gs = fig.add_gridspec(3, 3, hspace=0.35, wspace=0.3)
    for col_i, (atom, color, label) in enumerate(atoms):
        ax = fig.add_subplot(gs[0, col_i])
        for stage in STAGE_ORDER:
            sub = tr[tr['stage'] == stage]
            if sub.empty: continue
            marg1 = sub.groupby('lag1_min')[atom].mean()
            ax.plot(marg1.index, marg1.values, color=STAGE_COLORS[stage], lw=2, label=f'{stage} (lag₁)')
            marg2 = sub.groupby('lag2_min')[atom].mean()
            ax.plot(marg2.index, marg2.values, color=STAGE_COLORS[stage], lw=2, ls='--', alpha=0.7)
        ax.set_xlabel('Lag (min)'); ax.set_ylabel(f'{label} (bits)')
        ax.set_title(f'{label}\n(solid=lag₁ marginal, dashed=lag₂ marginal)', fontweight='bold', fontsize=10)
        ax.grid(alpha=0.3)
        if col_i == 0: ax.legend(fontsize=7, ncol=1)
    for col_i, (atom, color, label) in enumerate(atoms):
        ax = fig.add_subplot(gs[1, col_i])
        for stage in STAGE_ORDER:
            sub = tr[tr['stage'] == stage]
            if sub.empty: continue
            grp = sub.groupby('mean_lag')[atom].agg(['mean', 'sem']).reset_index()
            ax.plot(grp['mean_lag'], grp['mean'], color=STAGE_COLORS[stage], lw=2, label=stage)
            ax.fill_between(grp['mean_lag'], grp['mean'] - grp['sem'], grp['mean'] + grp['sem'],
                            color=STAGE_COLORS[stage], alpha=0.12)
        ax.set_xlabel('Mean lag  (lag₁+lag₂)/2  (min)'); ax.set_ylabel(f'{label} (bits)')
        ax.set_title(f'{label} vs absolute timescale', fontweight='bold', fontsize=10); ax.grid(alpha=0.3)
        if col_i == 0: ax.legend(fontsize=7)
    rng = np.random.default_rng(42); n_boot = 1000
    com_atoms = [('synergy', 'red', 'Synergy'), ('redundancy', 'green', 'Redundancy')]
    for col_i, (atom, color, label) in enumerate(com_atoms):
        ax = fig.add_subplot(gs[2, col_i])
        means, ci_lo, ci_hi, present = [], [], [], []
        for stage in STAGE_ORDER:
            sub = tr[tr['stage'] == stage]
            if sub.empty: continue
            present.append(stage)
            window_coms = []
            for w, wdf in sub.groupby('time_min'):
                weights = wdf[atom].values; total = weights.sum()
                if total > 0: window_coms.append(np.sum(weights * wdf['mean_lag'].values) / total)
            window_coms = np.array(window_coms)
            if len(window_coms) == 0: means.append(np.nan); ci_lo.append(np.nan); ci_hi.append(np.nan); continue
            means.append(np.mean(window_coms))
            boot_means = np.array([np.mean(rng.choice(window_coms, size=len(window_coms), replace=True)) for _ in range(n_boot)])
            ci_lo.append(np.percentile(boot_means, 2.5)); ci_hi.append(np.percentile(boot_means, 97.5))
        x = np.arange(len(present)); colors_bar = [STAGE_COLORS[s] for s in present]
        errs = np.array([[m - lo, hi - m] for m, lo, hi in zip(means, ci_lo, ci_hi)]).T
        ax.bar(x, means, color=colors_bar, edgecolor='white', linewidth=0.5, alpha=0.85)
        ax.errorbar(x, means, yerr=errs, fmt='none', ecolor='black', capsize=4, lw=1.2)
        ax.set_xticks(x); ax.set_xticklabels(present)
        ax.set_ylabel('Characteristic timescale (min)'); ax.set_xlabel('Sleep stage'); ax.grid(axis='y', alpha=0.3)
        com_groups = {}
        for stage in STAGE_ORDER:
            sub = tr[tr['stage'] == stage]
            if sub.empty: continue
            wcoms = []
            for w, wdf in sub.groupby('time_min'):
                wts = wdf[atom].values; tot = wts.sum()
                if tot > 0: wcoms.append(np.sum(wts * wdf['mean_lag'].values) / tot)
            if wcoms: com_groups[stage] = np.array(wcoms)
        grp_list = [v for v in com_groups.values() if len(v) > 0]
        if len(grp_list) >= 2:
            H, p = kruskal(*grp_list)
            ax.set_title(f'{label} center-of-mass\nKW: H={H:.1f}, p={p:.1e}', fontweight='bold', fontsize=10)
        else:
            ax.set_title(f'{label} center-of-mass\n(bootstrap 95% CI)', fontweight='bold', fontsize=10)
    ax_tab = fig.add_subplot(gs[2, 2]); ax_tab.axis('off')
    table_data = []
    for atom, _, label in com_atoms:
        for stage in STAGE_ORDER:
            sub = tr[tr['stage'] == stage]
            if sub.empty: continue
            window_coms = []
            for w, wdf in sub.groupby('time_min'):
                weights = wdf[atom].values; total = weights.sum()
                if total > 0: window_coms.append(np.sum(weights * wdf['mean_lag'].values) / total)
            if window_coms:
                m = np.mean(window_coms); s = np.std(window_coms) / np.sqrt(len(window_coms))
                table_data.append([label, stage, f'{m:.2f}', f'±{s:.2f}'])
    if table_data:
        tbl = ax_tab.table(cellText=table_data, colLabels=['Atom', 'Stage', 'CoM (min)', 'SEM'],
                           loc='center', cellLoc='center')
        tbl.auto_set_font_size(False); tbl.set_fontsize(8); tbl.scale(1, 1.3)
    ax_tab.set_title('Characteristic timescales', fontweight='bold', fontsize=10)
    plt.suptitle(f'Optimal timescale analysis ({channel})', fontsize=14, fontweight='bold')
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight'); plt.close()


# =============================================================================
# DISTRIBUTIONAL ANALYSIS ACROSS STAGES
# =============================================================================

def plot_stage_distribution_analysis(tr, channel, save_path=None):
    """Analyse how the *spread* of each PID metric differs across stages.

    For each stage we collect the per-window mean of each metric (one value per
    window, averaged over lag pairs). We then compare:
      Row 1 – violin plots of the metric values (absolute)
      Row 2 – CV (coefficient of variation = std/mean) per stage, with bootstrap CI
      Row 3 – per-lag-pair CV profile: how variable is each metric across windows at
              each timescale?  (low CV = homogeneous across recordings)

    Stats: Levene's test for equality of variances across stages (overall), plus
    Kruskal–Wallis on per-window CV values.
    """
    tr = tr.copy()
    tr['unique_total'] = tr['unique_0'] + tr['unique_1']
    tr['sr_ratio'] = np.where(tr['redundancy'] > 0,
                              tr['synergy'] / tr['redundancy'], np.nan)
    tr = tr[tr['stage'].isin(STAGE_ORDER)]
    present = [s for s in STAGE_ORDER if s in tr['stage'].unique()]
    if len(present) < 2:
        return

    metrics = [
        ('synergy',       'Reds',   'Synergy'),
        ('redundancy',    'Greens', 'Redundancy'),
        ('unique_total',  'Blues',  'Total Unique'),
        ('sr_ratio',      'Oranges','S / R Ratio'),
    ]

    # ---------- Row 1: violins of raw per-window means ----------
    # Per window: average across lag pairs
    win_agg = tr.groupby(['stage', 'window'])[
        ['synergy', 'redundancy', 'unique_total', 'sr_ratio']
    ].mean().reset_index()

    fig, axes = plt.subplots(3, len(metrics), figsize=(5 * len(metrics), 14))

    for ci, (metric, cmap, label) in enumerate(metrics):
        ax = axes[0, ci]
        groups = [win_agg.loc[win_agg['stage'] == s, metric].dropna().values
                  for s in present]
        parts = ax.violinplot([g for g in groups if len(g) > 0],
                              positions=range(len(present)),
                              showmeans=True, showmedians=True, showextrema=False)
        for i, pc in enumerate(parts['bodies']):
            pc.set_facecolor(STAGE_COLORS[present[i]])
            pc.set_alpha(0.6)
        parts['cmeans'].set_color('black')
        parts['cmedians'].set_color('grey')

        # Levene's test
        valid = [g for g in groups if len(g) >= 2]
        if len(valid) >= 2:
            stat_l, p_l = levene(*valid)
            stars = '***' if p_l < 0.001 else '**' if p_l < 0.01 else '*' if p_l < 0.05 else 'ns'
            ax.set_title(f'{label}\nLevene: W={stat_l:.1f}, p={p_l:.1e} {stars}',
                         fontweight='bold', fontsize=10)
        else:
            ax.set_title(label, fontweight='bold', fontsize=10)
        ax.set_xticks(range(len(present)))
        ax.set_xticklabels(present)
        ax.set_ylabel('bits' if metric != 'sr_ratio' else 'ratio')
        ax.grid(axis='y', alpha=0.3)

    # ---------- Row 2: per-window CV with bootstrap CI ----------
    rng = np.random.default_rng(42)
    n_boot = 1000

    for ci, (metric, cmap, label) in enumerate(metrics):
        ax = axes[1, ci]
        cv_groups = {}
        cv_means, cv_lo, cv_hi = [], [], []
        for stage in present:
            sub = win_agg[(win_agg['stage'] == stage) & win_agg[metric].notna()]
            vals = sub[metric].values
            if len(vals) < 3:
                cv_means.append(np.nan); cv_lo.append(np.nan); cv_hi.append(np.nan)
                continue
            # per-window CV: compute CV of each window's lag-pair values
            per_w_cvs = []
            stage_wins = tr[(tr['stage'] == stage) & tr[metric].notna()]
            for w, wdf in stage_wins.groupby('window'):
                v = wdf[metric].values
                m = v.mean()
                if m > 0 and len(v) > 1:
                    per_w_cvs.append(v.std() / m)
            per_w_cvs = np.array(per_w_cvs)
            if len(per_w_cvs) < 2:
                cv_means.append(np.nan); cv_lo.append(np.nan); cv_hi.append(np.nan)
                continue
            cv_groups[stage] = per_w_cvs
            cv_means.append(np.mean(per_w_cvs))
            boot = np.array([np.mean(rng.choice(per_w_cvs, len(per_w_cvs), replace=True))
                             for _ in range(n_boot)])
            cv_lo.append(np.percentile(boot, 2.5))
            cv_hi.append(np.percentile(boot, 97.5))

        x = np.arange(len(present))
        colors_bar = [STAGE_COLORS[s] for s in present]
        errs = np.array([[m - lo, hi - m]
                         for m, lo, hi in zip(cv_means, cv_lo, cv_hi)]).T
        ax.bar(x, cv_means, color=colors_bar, edgecolor='white', alpha=0.85)
        ax.errorbar(x, cv_means, yerr=errs, fmt='none', ecolor='black', capsize=4, lw=1.2)
        ax.set_xticks(x); ax.set_xticklabels(present)
        ax.set_ylabel('CV (std / mean)')
        ax.grid(axis='y', alpha=0.3)

        # KW on per-window CVs
        grp_list = [v for v in cv_groups.values() if len(v) >= 2]
        if len(grp_list) >= 2:
            H, p = kruskal(*grp_list)
            stars = '***' if p < 0.001 else '**' if p < 0.01 else '*' if p < 0.05 else 'ns'
            ax.set_title(f'{label} — within-window CV\nKW: H={H:.1f}, p={p:.1e} {stars}',
                         fontweight='bold', fontsize=10)

            # pairwise Mann-Whitney on CVs
            pairs = list(combinations([s for s in present if s in cv_groups], 2))
            pvals = []
            for s1, s2 in pairs:
                if len(cv_groups[s1]) >= 2 and len(cv_groups[s2]) >= 2:
                    _, pw = mannwhitneyu(cv_groups[s1], cv_groups[s2], alternative='two-sided')
                    pvals.append(pw)
                else:
                    pvals.append(1.0)
            adj_p = benjamini_hochberg(np.array(pvals))
            # annotate top-3 significant
            sig = [(pairs[i], adj_p[i]) for i in range(len(pairs)) if adj_p[i] < 0.05]
            sig.sort(key=lambda x: x[1])
            y_max = max([m for m in cv_means if not np.isnan(m)], default=0)
            for rank, ((s1, s2), pv) in enumerate(sig[:3]):
                i1, i2 = present.index(s1), present.index(s2)
                y = y_max * (1.05 + rank * 0.08)
                ax.plot([i1, i1, i2, i2], [y * 0.98, y, y, y * 0.98], lw=1, c='grey')
                star = '***' if pv < 0.001 else '**' if pv < 0.01 else '*'
                ax.text((i1 + i2) / 2, y, star, ha='center', va='bottom', fontsize=9)
        else:
            ax.set_title(f'{label} — within-window CV', fontweight='bold', fontsize=10)

    # ---------- Row 3: CV profile across lag pairs ----------
    for ci, (metric, cmap, label) in enumerate(metrics):
        ax = axes[2, ci]
        for stage in present:
            sub = tr[(tr['stage'] == stage) & tr[metric].notna()]
            if sub.empty:
                continue
            # group by lag pair, compute CV across windows
            lag_cv = sub.groupby(['lag1_min', 'lag2_min'])[metric].agg(['mean', 'std']).reset_index()
            lag_cv['cv'] = np.where(lag_cv['mean'] > 0, lag_cv['std'] / lag_cv['mean'], np.nan)
            lag_cv['mean_lag'] = (lag_cv['lag1_min'] + lag_cv['lag2_min']) / 2
            grp = lag_cv.groupby('mean_lag')['cv'].mean().reset_index()
            ax.plot(grp['mean_lag'], grp['cv'], color=STAGE_COLORS[stage],
                    lw=2, label=stage, alpha=0.85)
        ax.set_xlabel('Mean lag (min)')
        ax.set_ylabel('CV across windows')
        ax.set_title(f'{label} — CV by timescale', fontweight='bold', fontsize=10)
        ax.grid(alpha=0.3)
        if ci == 0:
            ax.legend(fontsize=8)

    plt.suptitle(f'Distributional analysis across stages ({channel})',
                 fontsize=14, fontweight='bold', y=1.01)
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        plt.close()


# =============================================================================
# CROSS-ELECTRODE COMPARISON
# =============================================================================

def plot_cross_electrode_comparison(all_data, save_path=None):
    """Compare PID across electrodes: one boxplot per atom, grouped by channel."""
    channels = [d['channel'] for d in all_data if d['tr'] is not None]
    if len(channels) < 2:
        return

    fig, axes = plt.subplots(1, 4, figsize=(20, 6))
    metrics = ['redundancy', 'synergy', 'unique_total', 'ratio']
    labels = ['Redundancy', 'Synergy', 'Total Unique', 'S/R Ratio']

    # aggregate per channel × stage
    rows = []
    for d in all_data:
        if d['tr'] is None:
            continue
        tr = common_lag_range(d['tr'])
        agg = tr.groupby(['time_min', 'stage']).agg(
            redundancy=('redundancy', 'mean'), synergy=('synergy', 'mean'),
            unique_0=('unique_0', 'mean'), unique_1=('unique_1', 'mean'),
        ).reset_index()
        agg['unique_total'] = agg['unique_0'] + agg['unique_1']
        agg['ratio'] = agg['synergy'] / agg['redundancy'].replace(0, np.nan)
        agg['channel'] = d['channel']
        rows.append(agg)

    combined = pd.concat(rows, ignore_index=True)
    combined = combined[combined['stage'].isin(STAGE_ORDER)]

    for ax, metric, label in zip(axes, metrics, labels):
        sns.boxplot(data=combined, x='stage', y=metric, hue='channel',
                    order=STAGE_ORDER, ax=ax, showfliers=False)
        ax.set_title(label, fontweight='bold')
        ax.set_ylabel(f'{label} (bits)' if metric != 'ratio' else 'S/R')
        ax.set_xlabel('Sleep stage')
        ax.grid(axis='y', alpha=0.3)
        if metric == 'ratio':
            ax.axhline(1.0, color='grey', ls='--', alpha=0.5)
        if ax != axes[0]:
            ax.get_legend().remove()
        else:
            ax.legend(fontsize=7, title='Channel')

    plt.suptitle('Cross-electrode PID comparison by sleep stage',
                 fontsize=14, fontweight='bold')
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight'); plt.close()


# =============================================================================
# MAIN
# =============================================================================

def generate_plots_for_channel(data, chash):
    """Generate all 15 plots for one channel."""
    ch = data['channel']
    ch_dir = data['ch_dir']
    tr = data['tr']
    stage_labels = data['stage_labels']
    h = chash  # short alias for filenames

    if tr is None:
        print(f"  Skipping {ch}: no time-resolved data found")
        return

    print(f"\n  Plotting {ch} …")

    print(f"    1/16 Global PID matrix")
    if data['global'] is not None:
        plot_global_matrix(data['global'], ch, save_path=ch_dir / f"global_pid_matrix_{h}.png")

    print(f"    2/16 Combined time series")
    if data['ar1_tr'] is not None and stage_labels is not None:
        plot_combined_timeseries(tr, data['ar1_tr'], stage_labels, ch,
                                save_path=ch_dir / f"combined_timeseries_{h}.png")

    print(f"    3/16 Time × Lag heatmaps")
    if stage_labels is not None:
        plot_time_lag_heatmaps(tr, stage_labels, ch, save_path=ch_dir / f"time_lag_heatmaps_{h}.png")

    print(f"    4/16 Stage comparison")
    plot_stage_comparison(tr, ch, save_path=ch_dir / f"stage_comparison_{h}.png")

    print(f"    5/16 Lag-difference heatmap")
    if stage_labels is not None:
        plot_lagdiff_heatmap(tr, stage_labels, ch, save_path=ch_dir / f"lagdiff_heatmap_{h}.png")

    print(f"    6/16 Global PID vs AR(1)")
    if data['global'] is not None and data['ar1_global'] is not None:
        plot_global_matrix_vs_ar1(data['global'], data['ar1_global'], ch,
                                  save_path=ch_dir / f"global_pid_vs_ar1_{h}.png")

    print(f"    7/16 Stage comparison vs AR(1)")
    if data['ar1_tr'] is not None:
        plot_stage_comparison_vs_ar1(tr, data['ar1_tr'], ch,
                                     save_path=ch_dir / f"stage_comparison_vs_ar1_{h}.png")

    print(f"    8/16 Autocorrelation vs PID")
    if data['autocorr'] is not None and stage_labels is not None:
        plot_autocorrelation_vs_pid(data['autocorr'], tr, stage_labels, ch,
                                    save_path=ch_dir / f"autocorrelation_vs_pid_{h}.png")

    print(f"    9/16 S/R ratio vs Autocorrelation")
    if data['autocorr'] is not None:
        plot_sr_ratio_vs_autocorr(data['autocorr'], tr, ch,
                                  save_path=ch_dir / f"sr_ratio_vs_autocorr_{h}.png")

    print(f"   10/16 PID per-stage matrices")
    plot_pid_per_stage_matrix(tr, ch, save_path=ch_dir / f"pid_per_stage_matrix_{h}.png")

    print(f"   11/16 Atom fractions")
    plot_atom_fractions(tr, ch, save_path=ch_dir / f"atom_fractions_{h}.png")

    print(f"   12/16 NREM→REM cycles")
    if stage_labels is not None:
        plot_nrem_rem_cycles(tr, stage_labels, ch, save_path=ch_dir / f"nrem_rem_cycles_{h}.png")

    print(f"   13/16 Effect sizes")
    plot_effect_sizes(tr, ch, save_path=ch_dir / f"effect_sizes_{h}.png")

    print(f"   14/16 Block-permutation significance")
    if data['global'] is not None and data['null_vals'] is not None:
        plot_block_permutation(data['global'], data['null_vals'], ch,
                               save_path=ch_dir / f"block_permutation_{h}.png")

    print(f"   15/16 Optimal timescales")
    plot_optimal_timescales(tr, ch, save_path=ch_dir / f"optimal_timescales_{h}.png")

    print(f"   16/16 Distribution analysis")
    plot_stage_distribution_analysis(tr, ch, save_path=ch_dir / f"stage_distributions_{h}.png")

    print(f"  ✓ {ch} done — {ch_dir}")


def main():
    parser = argparse.ArgumentParser(description="Plot PID results across EEG electrodes")
    parser.add_argument('--channels', nargs='+', default=None,
                        help="Channel short names (e.g. C3 O1 F3). Default: all with data")
    parser.add_argument('--force', action='store_true',
                        help="Regenerate plots even if they already exist")
    args = parser.parse_args()

    all_configs = _discover_all_params()
    if not all_configs:
        print("No params JSON found with matching data. Run eeg_sleep_compute.py first.")
        sys.exit(1)

    print("=" * 70)
    print("EEG SLEEP — PLOT PID RESULTS")
    print(f"Started : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"Found {len(all_configs)} config(s) with data")
    print("=" * 70)

    total_plotted = 0

    for params, chash in all_configs:
        _apply_params(params)
        bands = params.get("BANDS", None)

        print(f"\n{'─'*70}")
        print(f"Config {chash}: W={WINDOW_SEC}s, lags={MAX_LAG_MIN}min, "
              f"bins={N_BINS}, dur={DURATION_HOURS}h, "
              f"bands={'broadband' if not bands else list(bands.keys())}")
        print(f"{'─'*70}")

        # Discover channels with data for this hash
        if args.channels:
            ch_shorts = args.channels
        else:
            if bands:
                ch_shorts = sorted([
                    d.name for d in RESULTS_DIR.iterdir()
                    if d.is_dir() and any(
                        (d / b / f"timeresolved_pid_filtered_{chash}.csv").exists()
                        for b in bands)])
            else:
                ch_shorts = sorted([d.name for d in RESULTS_DIR.iterdir()
                                    if d.is_dir() and (d / f"timeresolved_pid_filtered_{chash}.csv").exists()])
        if not ch_shorts:
            print(f"  No channel data for hash {chash}, skipping")
            continue

        print(f"  Channels: {ch_shorts}")

        # Load all channel data
        all_data = []
        for ch_short in ch_shorts:
            if bands:
                for band_name in bands:
                    data = load_channel_data(ch_short, chash, band_name=band_name)
                    if data is not None:
                        all_data.append(data)
            else:
                data = load_channel_data(ch_short, chash)
                if data is not None:
                    all_data.append(data)

        # Generate per-channel plots (skip if first plot already exists, unless --force)
        for data in all_data:
            ch_dir = data['ch_dir']
            first_plot = ch_dir / f"global_pid_matrix_{chash}.png"
            if first_plot.exists() and not args.force:
                print(f"  {data['channel']}: plots exist, skipping (use --force to regenerate)")
                continue
            generate_plots_for_channel(data, chash)
            total_plotted += 1

        # Cross-electrode comparison
        if len(all_data) >= 2:
            cross_path = RESULTS_DIR / f"cross_electrode_comparison_{chash}.png"
            if not cross_path.exists() or args.force:
                print(f"\n  Cross-electrode comparison …")
                plot_cross_electrode_comparison(all_data, save_path=cross_path)

    print(f"\n{'='*70}")
    print(f"ALL DONE — {total_plotted} channel×config sets plotted")
    print(f"Finished : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")


if __name__ == "__main__":
    main()
